services:
  worker:
    build: .
    environment:
      STRING_SESSION: $STRING_SESSION
      APP_ID: $APP_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      DATABASE_URL: $DATABASE_URI  # defaults to None
      TG_BOT_TOKEN: $TG_BOT_TOKEN # Not mandatory
      LOG_CHANNEL: $LOG_CHANNEL # Not mandatory
